name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 2545
      DATABASE_NAME: api
      DATABASE_USERNAME: postgres
      SECRET_KEY: 678e976ed7f82256140510cca53136eb50877d9379817b1660db4a0bcac134bb
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.14
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pip install pytest
          pytest -q --disable-warnings
                